Models/AlunoViewModel.cs
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace SistemaProfessoresAlunos.Models
{
    public class AlunoViewModel
    {
        public int Id { get; set; }
        
        public string Nome { get; set; }
        
        public float Mensalidade { get; set; }
        
        public DateTime DataVencimento { get; set; }
        
        public int ProfessorId { get; set; }

        public string NomeProfessor { get; set; }

        public IFormFile Arquivo { get; set; }
    }
}

Controllers/AlunoController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using SistemaProfessoresAlunos.DAL;
using SistemaProfessoresAlunos.Entidades;
using SistemaProfessoresAlunos.Models;

namespace SistemaProfessoresAlunos.Controllers
{
    public class AlunoController : Controller
    {
        protected ApplicationDbContext mContext;

        public AlunoController(ApplicationDbContext context)

        {
            mContext = context;
        }

        public IActionResult Cadastro(AlunoViewModel viewAluno)
        {
            if (ModelState.IsValid)
            {
                Aluno aluno = new Aluno()
                {
                    Nome = viewAluno.Nome,
                    Mensalidade = viewAluno.Mensalidade,
                    DataVencimento = viewAluno.DataVencimento,
                    ProfessorId = viewAluno.ProfessorId
                };

                mContext.Aluno.Add(aluno);


                mContext.SaveChanges();
            }

            return RedirectToAction("Consulta");
        }
        public IActionResult Consulta(int professorId)
        {
            IEnumerable<AlunoViewModel> alunos = (from Aluno in mContext.Aluno
                                                  join professor in mContext.Professor on Aluno.ProfessorId equals professor.Id
                                                  where Aluno.ProfessorId == professorId
                                                  select new AlunoViewModel
                                                  {
                                                      Id = Aluno.Id,
                                                      Nome = Aluno.Nome,
                                                      Mensalidade = Aluno.Mensalidade,
                                                      ProfessorId = Aluno.ProfessorId,
                                                      DataVencimento = Aluno.DataVencimento,
                                                      NomeProfessor = professor.Nome
                                                  }).ToList();            
            mContext.Dispose();
            return View(alunos);
        }        

        [HttpPost]
        public IActionResult ConfirmarExclusao(string alunosExclusaoId)
        {
            var ids = alunosExclusaoId.Split(',');
            int professorId = 0;

            foreach(var id in ids)
            {
                if(id != "")
                {
                    Aluno aluno = mContext.Aluno.Where(a => a.Id == Convert.ToInt32(id)).FirstOrDefault();
                    professorId = aluno.ProfessorId;
                    mContext.Attach(aluno);
                    mContext.Remove(aluno);
                }                
            }

            mContext.SaveChanges();
            return RedirectToAction("Consulta", new { professorId = professorId });
        }       
    }
}

Views/Aluno/Cadastro.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

        

Views/Aluno/Consulta.cshtml
@{
    ViewData["Title"] = "Alunos";
}

@using SistemaProfessoresAlunos.Models;    
@model List<AlunoViewModel>;

@{ 
    var professorId = Context.Request.Query["ProfessorId"].ToString();
}



<div class="row">
    <div class="col-md-2">
        <h4>Inserir novos alunos</h4>
        <input type="button" class="btn btn-primary" value="Inserir Alunos" name="btnInserirAlunos" id="btnInserirAlunos" onclick="InserirAlunos(@professorId)" />
    </div>
    <div class="col-md-8">
        <div class="text-center">
            <h2>Alunos</h2>
        </div>
        <hr />
        <form asp-controller="Aluno" asp-action="ConfirmarExclusao" method="post">
            <input type="hidden" id="alunosExclusaoId" value=""/>
        </form>
        <table class="table table-bordered">
            <thead>
                <tr>
                    <td class="text-center"><b>Nome</b></td>
                    <td class="text-center"><b>Mensalidade</b></td>
                    <td class="text-center"><b>Data de Vencimento</b></td>
                    <td class="text-center"><b>Nome do Professor</b></td>
                    <td class="text-center"><b>Excluir Aluno</b></td>
                </tr>
            </thead>
            <tbody>
                @{
                    if (Model.Count() > 0)
                    {
                        foreach (var item in Model)
                        {
                            <tr>
                                <td class="text-center">@item.Nome</td>
                                <td class="text-center">R$ @item.Mensalidade.ToString("n2")</td>
                                <td class="text-center">@item.DataVencimento.ToString("dd/MM/yyyy")</td>
                                <td class="text-center">@item.NomeProfessor</td>
                                <td class="text-center" style="cursor:pointer"> <input type="checkbox" value="@item.Id" /></td>
                            </tr>
                        }
                    }
                }
            </tbody>
        </table>
        <br />
        <input type="button" class="btn btn-primary" value="Confirmar Exclusão de Alunos" name="btnConfirmarExclusao" id="btnConfirmarExclusao" onclick="ConfirmarExclusao();" />
    </div>
    <div class="col-md-2"></div>
</div>

<script>   
    function InserirAlunos(id) {
        window.location = window.origin + "\\Arquivo\\Index?ProfessorId=" + id;
    }

    function ExcluirAluno(id) {
        if (document.getElementById("alunosExclusaoId").value == "") {
            document.getElementById("alunosExclusaoId").value = id;
        }
        else {
            var valor = document.getElementById("alunosExclusaoId").value.split(',');
            if (valor.find(element => element == id) === undefined) {
                document.getElementById("alunosExclusaoId").value = "";
                document.getElementById("alunosExclusaoId").value = valor + ',' + id;
            }            
        }
    }

    function ConfirmarExclusao() {
        var ids = "";
        var checkboxes = document.querySelectorAll('input[type=checkbox]:checked')

        for (var i = 0; i < checkboxes.length; i++) {
            ids += checkboxes[i].value + ',';
        }

        if (ids.replace(',', '') != "") {
            $.ajax({
                type: "POST",
                url: '@Url.Action("ConfirmarExclusao", "Aluno")',
                data: { "alunosExclusaoId": ids },
                success: function () {
                    alert('sucesso');
                    location.reload();
                }
            });
        }
        else {
            alert('Selecione pelo menos 1 aluno!');
        }

        
    }
</script>